server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsmortgage
    username: root
    password: rootpassword
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
